name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [alpine, stretch, centos7-devtoolset8, snapcraft]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.arch }}
          file: ${{ matrix.arch }}/Dockerfile
          tags: ghcr.io/redstonewizard08/vscode-linux-build-agent:${{ matrix.arch }}
          push: true
          platforms: linux/arm64,linux/amd64

